"""Hidden Markov Model for per-team goal sequences.

This module implements a Gaussian-emission HMM trained via Baum-Welch
(forward-backward) with log-space arithmetic for numerical stability over
long sequences.  The primary use case is modelling a football team's latent
"form" state from their historical goals-scored-per-match.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np

# ---------------------------------------------------------------------------
# Configuration & result types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class TeamHMMConfig:
    """Hyper-parameters for :class:`TeamHMM`.

    Attributes
    ----------
    n_states:
        Number of latent states (default 3 → bad-form / neutral / good-form).
    n_iter:
        Maximum Baum-Welch EM iterations.
    min_matches:
        Minimum matches required to train a team-specific HMM; teams with
        fewer matches fall back to a league-average HMM.
    seed:
        Seed for any random initialisation (note: current initialisation is
        deterministic, so this is a future-proofing parameter).
    regularization:
        Minimum variance floor to prevent degenerate state collapse.
    """

    n_states: int = 3
    n_iter: int = 50
    min_matches: int = 30
    seed: int = 42
    regularization: float = 1e-3


@dataclass(frozen=True)
class HMMResult:
    """Prediction output from a trained :class:`TeamHMM`.

    Attributes
    ----------
    state_probs:
        Posterior probability distribution over latent states at the final
        time-step, shape ``(K,)``.
    expected_goals:
        Expected number of goals in the next match,
        ``sum_k state_probs[k] * means[k]``.
    state_entropy:
        Entropy of ``state_probs`` in nats.
    means:
        Per-state mean parameters of the Gaussian emission distributions,
        shape ``(K,)``.
    vars:
        Per-state variance parameters, shape ``(K,)``.
    """

    state_probs: np.ndarray = field(repr=False)
    expected_goals: float
    state_entropy: float
    means: np.ndarray = field(repr=False)
    vars: np.ndarray = field(repr=False)


# ---------------------------------------------------------------------------
# TeamHMM — Gaussian-emission HMM via Baum-Welch
# ---------------------------------------------------------------------------


class TeamHMM:
    """Gaussian-observation Hidden Markov Model for a single team.

    The model assumes a sequence of 1-D observations (goals scored per match)
    generated by a discrete latent state with K values.  Each state emits
    goals according to a Gaussian distribution with state-specific mean and
    variance.

    Parameters are learned via the Baum-Welch algorithm (a special case of EM
    for HMMs) implemented entirely in log-space to avoid underflow.

    Parameters
    ----------
    config:
        Hyper-parameters (number of states, iterations, regularisation, etc.).
    """

    def __init__(self, config: TeamHMMConfig) -> None:
        self.config = config
        self._rng = np.random.default_rng(config.seed)
        # Learned parameters (set by fit)
        self.means_: np.ndarray | None = None
        self.vars_: np.ndarray | None = None
        self.trans_: np.ndarray | None = None
        self.start_prob_: np.ndarray | None = None

    # -- public API ----------------------------------------------------------

    def fit(self, goals: np.ndarray) -> None:
        """Estimate HMM parameters via Baum-Welch EM.

        Parameters
        ----------
        goals:
            1-D array of goal counts (goals scored per match by the team).
        """
        goals = np.asarray(goals, dtype=float)
        if goals.ndim != 1:
            raise ValueError(f"goals must be 1-D, got shape {goals.shape}")

        self._init_params(goals)
        K = self.config.n_states
        n_iter = self.config.n_iter

        for _ in range(n_iter):
            log_emit = self._log_emit(goals)
            log_alpha = self._forward(log_emit)
            log_beta = self._backward(log_emit)
            log_lik = self._log_likelihood(log_alpha)

            # -- E-step: posterior probabilities ------------------------------
            # gamma[t, k] = P(state_t = k | observations)
            gamma = np.exp(log_alpha + log_beta - log_lik)

            # xi[t, i, j] = P(state_t = i, state_{t+1}=j | observations)
            T = len(goals)
            xi = np.zeros((T - 1, K, K))
            log_trans_safe = np.log(np.maximum(self.trans_, 1e-12))
            for t in range(T - 1):
                xi[t] = np.exp(
                    log_alpha[t, :, np.newaxis]
                    + log_trans_safe
                    + log_emit[t + 1, np.newaxis, :]
                    + log_beta[t + 1, np.newaxis, :]
                    - log_lik
                )

            # -- M-step: parameter updates -----------------------------------

            # Start probabilities
            self.start_prob_ = gamma[0]
            self.start_prob_ /= self.start_prob_.sum()

            # Transition matrix
            for i in range(K):
                denom = np.sum(xi[:, i, :])
                if denom > self.config.regularization:
                    self.trans_[i, :] = np.sum(xi[:, i, :], axis=0) / denom
            # Renormalize rows
            self.trans_ /= self.trans_.sum(axis=1, keepdims=True)

            # Means (weighted by posterior state occupancy)
            for k in range(K):
                denom = np.sum(gamma[:, k])
                if denom > self.config.regularization:
                    self.means_[k] = np.sum(gamma[:, k] * goals) / denom

            # Variances (with floor to prevent collapse)
            for k in range(K):
                denom = np.sum(gamma[:, k])
                if denom > self.config.regularization:
                    var = np.sum(gamma[:, k] * (goals - self.means_[k]) ** 2) / denom
                    self.vars_[k] = max(var, self.config.regularization)

    def predict_next(self, goals: np.ndarray) -> HMMResult:
        """Run the forward algorithm on *full history* and return next-match predictions.

        Parameters
        ----------
        goals:
            1-D array of historical goal counts for this team (all matches
            *before* the target match).  Must have length ≥ 1.

        Returns
        -------
        HMMResult
            State distribution at the final time-step, expected goals,
            state entropy, and the learned emission parameters.
        """
        goals = np.asarray(goals, dtype=float)
        if goals.ndim != 1:
            raise ValueError(f"goals must be 1-D, got shape {goals.shape}")
        if len(goals) == 0:
            # No history: return uniform state probs over the learned means
            K = self.config.n_states
            uniform = np.full(K, 1.0 / K)
            eg = float(uniform @ self.means_)
            ent = float(-np.sum(uniform * np.log(uniform)))
            return HMMResult(
                state_probs=uniform,
                expected_goals=eg,
                state_entropy=ent,
                means=self.means_.copy(),
                vars=self.vars_.copy(),
            )

        log_emit = self._log_emit(goals)
        log_alpha = self._forward(log_emit)
        log_lik = self._log_likelihood(log_alpha)

        # State probabilities at the *last* observed time-step.
        state_probs = np.exp(log_alpha[-1] - log_lik)

        expected_goals = float(state_probs @ self.means_)

        # Shannon entropy in nats: -sum_k p_k log p_k
        mask = state_probs > 0.0
        state_entropy = float(-np.sum(state_probs[mask] * np.log(state_probs[mask])))

        return HMMResult(
            state_probs=state_probs,
            expected_goals=expected_goals,
            state_entropy=state_entropy,
            means=self.means_.copy(),
            vars=self.vars_.copy(),
        )

    # -- internal helpers ----------------------------------------------------

    def _init_params(self, goals: np.ndarray) -> None:
        """Deterministic parameter initialisation."""
        K = self.config.n_states
        n = len(goals)
        reg = self.config.regularization

        # Means: evenly-spaced quantile-based initialisation.
        if n >= K:
            sorted_g = np.sort(goals)
            indices = np.linspace(0, n - 1, K).astype(int)
            self.means_ = sorted_g[indices].astype(float)
        else:
            self.means_ = np.linspace(goals.min(), goals.max(), K)

        # Variances: global observation variance (shared initial value).
        obs_var = float(np.var(goals)) if n > 1 else 1.0
        self.vars_ = np.full(K, max(obs_var, reg))

        # Transition matrix: high self-transition (~0.7), rest to neighbours.
        self.trans_ = np.zeros((K, K))
        if K == 1:
            self.trans_[0, 0] = 1.0
        else:
            for i in range(K):
                self.trans_[i, i] = 0.7
                neighbours = []
                if i > 0:
                    neighbours.append(i - 1)
                if i < K - 1:
                    neighbours.append(i + 1)
                leak = 0.3 / len(neighbours)
                for j in neighbours:
                    self.trans_[i, j] = leak

        # Start probabilities: uniform.
        self.start_prob_ = np.full(K, 1.0 / K)

    @staticmethod
    def _logsumexp(x: np.ndarray, axis: int = -1) -> np.ndarray:
        """Log-sum-exp trick for numerical stability.

        Returns an array with the same number of dimensions as *x* minus the
        reduced axis (consistent with ``np.sum``).
        """
        x_max = np.max(x, axis=axis, keepdims=True)
        result = np.log(np.sum(np.exp(x - x_max), axis=axis)) + np.squeeze(x_max)
        return result

    def _log_emit(self, goals: np.ndarray) -> np.ndarray:
        """Log-emission probabilities for every state at every time-step.

        Returns shape ``(T, K)``.
        """
        T = len(goals)
        K = self.config.n_states
        log_emit = np.empty((T, K))
        for k in range(K):
            mu = self.means_[k]
            var = self.vars_[k]
            # log N(x; mu, var) = -0.5 * log(2*pi*var) - 0.5*(x - mu)^2 / var
            log_emit[:, k] = -0.5 * np.log(2.0 * math.pi * var) - 0.5 * (goals - mu) ** 2 / var
        return log_emit

    def _forward(self, log_emit: np.ndarray) -> np.ndarray:
        """Forward algorithm in log-space.

        Parameters
        ----------
        log_emit:
            Log-emission probabilities, shape ``(T, K)``.

        Returns
        -------
        log_alpha:
            Log forward probabilities, shape ``(T, K)``.
        """
        T, K = log_emit.shape
        log_alpha = np.empty((T, K))
        # Floor at 1e-12 to avoid log(0) — Baum-Welch may produce rows with
        # very small or zero entries; the floor only affects computation of
        # states that have effectively-zero probability.
        log_trans = np.log(np.maximum(self.trans_, 1e-12))

        # t = 0
        log_alpha[0] = np.log(np.maximum(self.start_prob_, 1e-12)) + log_emit[0]

        # t = 1 .. T-1
        for t in range(1, T):
            # log_alpha[t, k] = log_emit[t,k] + logsumexp_i(log_alpha[t-1,i] + log_trans[i,k])
            log_alpha[t] = log_emit[t] + self._logsumexp(
                log_alpha[t - 1, :, np.newaxis] + log_trans, axis=0
            )

        return log_alpha

    def _backward(self, log_emit: np.ndarray) -> np.ndarray:
        """Backward algorithm in log-space.

        Parameters
        ----------
        log_emit:
            Log-emission probabilities, shape ``(T, K)``.

        Returns
        -------
        log_beta:
            Log backward probabilities, shape ``(T, K)``.
        """
        T, K = log_emit.shape
        log_beta = np.empty((T, K))
        log_trans = np.log(np.maximum(self.trans_, 1e-12))

        # t = T-1
        log_beta[T - 1] = 0.0

        # t = T-2 .. 0
        for t in range(T - 2, -1, -1):
            # log_beta[t,i] = logsumexp_j(log_trans[i,j] + log_emit[t+1,j] + log_beta[t+1,j])
            log_beta[t] = self._logsumexp(
                log_trans + log_emit[t + 1, np.newaxis, :] + log_beta[t + 1, np.newaxis, :],
                axis=1,
            )

        return log_beta

    def _log_likelihood(self, log_alpha: np.ndarray) -> float:
        """Log-likelihood of the observations under the current parameters."""
        return float(self._logsumexp(log_alpha[-1]))


# ---------------------------------------------------------------------------
# Poisson conversion helper
# ---------------------------------------------------------------------------


def expected_goals_to_p_over25(lambda_home: float, lambda_away: float) -> float:
    """Probability of *over 2.5 total goals* under independent Poisson.

    ``total_goals ~ Poisson(lambda_home) + Poisson(lambda_away)``.

    The probability is computed via direct summation:

    ``P(over 2.5) = 1 - P(total ≤ 2)``

    where ``P(total ≤ 2)`` is the sum over all pairs ``(i, j)`` with
    ``i + j ≤ 2``.  The lambdas are clipped to ``[0.05, 5.0]`` before
    computation.

    Parameters
    ----------
    lambda_home:
        Expected home goals (rate parameter).
    lambda_away:
        Expected away goals (rate parameter).

    Returns
    -------
    float
        Probability that total goals exceed 2.5.
    """
    lam_h = float(np.clip(lambda_home, 0.05, 5.0))
    lam_a = float(np.clip(lambda_away, 0.05, 5.0))

    # Cache Poisson probabilities for efficiency.
    def _poisson_pmf(k: int, lam: float) -> float:
        return math.exp(-lam) * (lam**k) / math.factorial(k)

    # P(total <= 2) = sum_{i+j <= 2} P_home(i) * P_away(j)
    p_le_2 = 0.0
    for total in range(3):  # total = 0, 1, 2
        for i in range(total + 1):
            j = total - i
            p_le_2 += _poisson_pmf(i, lam_h) * _poisson_pmf(j, lam_a)

    return float(1.0 - p_le_2)
